"""Generate and launch per-node overnight scripts from cluster/overnight_plan.conf.
Each node gets universe-1/results/life/overnight.sh: GPU chains wait until no exp06b_node.py driver runs on the node, then run their
runs in order (one chain per GPU slot, chains in parallel); CPU runs start at once under nice 19. Every run writes
results/life/<run>/{run.log,stats.csv,final.bin,final.ppm,t*.ppm} and results/life/overnight_status.txt gets a line per start/end.
usage: python cluster/overnight.py [--dry] [--nodes adler40,knecht24,...]"""
import argparse, subprocess, sys
from collections import defaultdict
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
ap = argparse.ArgumentParser(); ap.add_argument('--dry', action='store_true'); ap.add_argument('--nodes'); args = ap.parse_args()
plan = defaultdict(lambda: defaultdict(list))
for line in (ROOT / 'cluster/overnight_plan.conf').read_text().splitlines():
    if not line.strip() or line.startswith('#'): continue
    node, slot, engine, name, opts = (x.strip() for x in line.split('|')); plan[node][slot].append((engine, name, opts))
NL = chr(10)
for node, slots in plan.items():
    if args.nodes and node not in args.nodes.split(','): continue
    lines = ['#!/bin/sh', '# generated by cluster/overnight.py', 'cd "$HOME/universe-1" || exit 1', 'mkdir -p results/life', 'S=results/life/overnight_status.txt',
             'echo "$(date -u +%FT%TZ) overnight.sh started on $(hostname)" >> $S']
    def chain(slot, runs, wait):
        body = ['(']
        if wait: body.append('  while pgrep -f "^python3 cluster/exp06b_node.py" >/dev/null 2>&1; do sleep 60; done')
        for engine, name, opts in runs:
            gpu = '' if slot == 'cpu' else f'--gpu {slot} '
            nice = 'nice -n 19' if slot == 'cpu' else 'nice -n 10'
            body += [f'  mkdir -p results/life/{name}', f'  echo "$(date -u +%FT%TZ) start {name} slot {slot}" >> $S',
                     f'  {nice} {engine} {gpu}{opts} --out-dir results/life/{name} --dump-final > results/life/{name}/run.log 2>&1',
                     f'  echo "$(date -u +%FT%TZ) end {name} exit $?" >> $S']
        body.append(') &'); return body
    for slot, runs in slots.items(): lines += chain(slot, runs, wait=(slot != 'cpu'))
    lines += ['wait', 'echo "$(date -u +%FT%TZ) overnight.sh finished" >> $S']
    script = NL.join(lines) + NL
    local = ROOT / f'results/life/overnight_{node}.sh'; local.write_text(script, newline=NL)
    print(f'== {node}: {sum(len(r) for r in slots.values())} runs on slots {list(slots)}')
    if args.dry: print(script); continue
    subprocess.run(['scp', '-q', str(local), f'{node}:universe-1/results/life/overnight.sh'], check=True)
    subprocess.run(['ssh', '-o', 'BatchMode=yes', node, 'cd universe-1 && chmod +x results/life/overnight.sh && (setsid nohup sh results/life/overnight.sh > results/life/overnight.out 2>&1 < /dev/null & disown); sleep 2; pgrep -af "overnight.sh" | grep -v pgrep | head -2'], check=True)
